version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: newgyo-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10

# Spring Boot Application
  spring:
    image: yul554/newgyo-spring:latest
    container_name: newgyo-spring
    depends_on:
      mysql :
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DB_NAME: ${SPRING_DB_NAME}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      PASSPHRASE: ${PASSPHRASE}
      SALT: ${SALT}
      SERVER_ADDRESS: 0.0.0.0
    restart: on-failure

# Python Application
  python:
    build:
      context: ./newgyo-py
    image: newgyo-python
    container_name: newgyo-python-srv
    ports:
      - "8000:8000"
    environment:
        CHAT_KEY: ${PYTHON_HOST}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        SERVER_ADDRESS: 0.0.0.0
    restart: always

networks:
  newgyo-network:
    driver: bridge

volumes:
  mysql_data:
